const RESET_GUEST = "RESET_GUEST";
const SET_PAGE = "SET_PAGE";
const SET_GUEST = "SET_GUEST";
const SET_GUEST_PARTIES = "SET_GUEST_PARTIES";
const SET_SEARCHRESULTS = "SET_SEARCHRESULTS";
const SET_PARTYDETAILS = "SET_PARTYDETAILS";
const SET_NEWPARTY_DETAILS = "SET_NEWPARTY_DETAILS";
const UPDATE_NEWPARTY_GUESTLIST = "UPDATE_NEWPARTY_GUESTLIST";
const RESET_NEWPARTY = "RESET_NEWPARTY";
const SET_PARTY = "SET_PARTY";
const SET_AVATARS = "SET_AVATARS";
const SET_GUEST_AVATAR = "SET_GUEST_AVATAR";
const SET_GUEST_AVATARDATA = "SET_GUEST_AVATARDATA";
const SET_EDITDETAILS = "SET_EDITDETAILS";
const RESET_EDITDETAILS = "RESET_EDITDETAILS";
const SET_ATTENDING = "SET_ATTENDING";
const ADD_SUPPLIES = "ADD_SUPPLIES";
const SET_PARTY_COMMENTS = "SET_PARTY_COMMENTS";
const SET_PARTYUNFORMATTED = "SET_PARTYUNFORMATTED";
const SET_PARTY_GUESTS = "SET_PARTY_GUESTS";
const SET_ALL_SUPPLIES = " SET_ALL_SUPPLIES";
const RESET_NEWPARTY_GUESTLIST = "RESET_NEWPARTY_GUESTLIST";

export {
  RESET_GUEST,
  SET_PAGE,
  SET_GUEST,
  SET_SEARCHRESULTS,
  SET_GUEST_PARTIES,
  SET_PARTYDETAILS,
  SET_NEWPARTY_DETAILS,
  UPDATE_NEWPARTY_GUESTLIST,
  RESET_NEWPARTY,
  SET_PARTY,
  SET_AVATARS,
  SET_GUEST_AVATAR,
  SET_GUEST_AVATARDATA,
  SET_EDITDETAILS,
  RESET_EDITDETAILS,
  SET_ATTENDING,
  ADD_SUPPLIES,
  SET_PARTY_COMMENTS,
  SET_PARTYUNFORMATTED,
  SET_PARTY_GUESTS,
  SET_ALL_SUPPLIES,
  RESET_NEWPARTY_GUESTLIST,
};
