const RESET_GUEST = "RESET_GUEST";
const SET_PAGE = "SET_PAGE";
const SET_GUEST = "SET_GUEST";
const SET_GUEST_PARTIES = "SET_GUEST_PARTIES";
const SET_SEARCHRESULTS = "SET_SEARCHRESULTS";

export {
  RESET_GUEST,
  SET_PAGE,
  SET_GUEST,
  SET_SEARCHRESULTS,
  SET_GUEST_PARTIES,
};
