const RESET_GUEST = "RESET_GUEST";
const SET_PAGE = "SET_PAGE";
const SET_GUEST = "SET_GUEST";
const SET_GUEST_PARTIES = "SET_GUEST_PARTIES";
const SET_SEARCHRESULTS = "SET_SEARCHRESULTS";
const SET_PARTYDETAILS = "SET_PARTYDETAILS";
const SET_NEWPARTY_DETAILS = "SET_NEWPARTY_DETAILS";
const UPDATE_NEWPARTY_GUESTLIST = "UPDATE_NEWPARTY_GUESTLIST";
const RESET_NEWPARTY = "RESET_NEWPARTY";

export {
  RESET_GUEST,
  SET_PAGE,
  SET_GUEST,
  SET_SEARCHRESULTS,
  SET_GUEST_PARTIES,
  SET_PARTYDETAILS,
  SET_NEWPARTY_DETAILS,
  UPDATE_NEWPARTY_GUESTLIST,
  RESET_NEWPARTY,
};
